// Fetch User by ID

import { generateOAuthDefaultNameValue } from '../utils/authHelpers.js';

/**
 * Gets user using custom <provider>:<id> id NOT autogenerated _id
 * */
export async function getUserById(db, id) {
  return await db.collection('users').findOne({ id });
}

/**
 * Gets user by username
 * */
export async function getUserByUsername(db, username) {
  return await db.collection('users').findOne({ username });
}

/**
 * Change username
 * */
export async function updateUsername(db, userid, newUsername) {
  return await db.collection('users').updateOne(
    { id: userid }, // Find the post by ID
    { $set: { username: newUsername } } // Update only the content field
  );
}

/**
 * Create new User (localAuth - with hashed password
 * */
export async function createUser(db, id, username, hashedPassword, email) {
  const newUser = {
    id: id,
    username: username,
    email: email || 'no-email@local.com',
    password: hashedPassword,
    verified: false,
    provider: 'local',
    createdAt: new Date(),
  };

  return await db.collection('users').insertOne(newUser);
}

/**
 * Find or create a user based on OAuth profile
 * */
export async function findOrCreateUser(db, profile, provider) {
  const userId = `${provider}:${profile.id}`;
  console.log('🔍 Checking user in DB:', userId); // Log user ID being checked

  let user = await getUserById(db, userId);

  if (!user) {
    console.log('🆕 User does not exist. Creating new user...');

    user = {
      id: userId,
      username: profile.displayName || generateOAuthDefaultNameValue(),
      email: profile.emails?.[0]?.value || `no-email@${provider}.com`,
      verified: false,
      provider,
      createdAt: new Date(),
    };

    const result = await db.collection('users').insertOne(user);
    console.log('✅ Insert result:', result); // Log insert result
  } else {
    console.log('✅ User found in DB:', user);
  }

  return user;
}

export async function setVerified(db, userId) {
  return await db.collection('users').updateOne({ id: userId }, { $set: { verified: true } });
}
