// Fetch User by ID
import bcrypt from 'bcrypt';
import crypto from 'crypto';

// Generate a unique 18-digit number
export function generateUserId() {
  const min = 100000; // Smallest 6-digit number
  const max = 999999; // Largest 6-digit number
  const randomNum = crypto.randomInt(min, max);
  return `local:${randomNum}`;
}
/**
 * Gets user using custom <provider>:<id> id NOT autogenerated _id
 * */
export async function getUserById(db, id) {
  return await db.collection('users').findOne({ id });
}

/**
 * Gets user by username
 * */
export async function getUserByUsername(db, username) {
  return await db.collection('users').findOne({ username });
}

/**
 * Change username
 * */
export async function updateUsername(db, userid, newUsername) {
  return await db.collection('users').updateOne(
    { id: userid }, // Find the post by ID
    { $set: { username: newUsername } } // Update only the content field
  );
}

/**
 * Create new User (localAuth - with hashed password
 * */
export async function createUser(db, username, password, email) {
  if (!username || !password) {
    throw new Error('Username and password required');
  }
  const hashedPassword = await bcrypt.hash(password, 10);

  const newUser = {
    id: generateUserId(),
    username: username,
    email: email || '',
    password: hashedPassword,
    role: 'registered',
    provider: 'local',
    createdAt: new Date(),
  };

  return await db.collection('users').insertOne(newUser);
}
/**
 * Find or create a user based on OAuth profile
 * */
export async function findOrCreateUser(db, profile, provider) {
  const userId = `${provider}:${profile.id}`;
  let user = await getUserById(db, userId);

  if (!user) {
    user = {
      id: userId,
      username: profile.displayName,
      email: profile.emails?.[0]?.value || '',
      role: 'registered',
      provider,
      createdAt: new Date(),
    };
    await db.collection('users').insertOne(user);
  }
  return user;
}

//Verify Password
export async function verifyPassword(user, password) {
  return await bcrypt.compare(password, user.password);
}
